FROM node:24-alpine

WORKDIR /app

# Копируем только файлы зависимостей для кэширования слоя
COPY package*.json ./

# Устанавливаем зависимости
RUN npm install

# Копируем остальное (хотя в dev режиме это перекроется волюмом)
COPY . .

CMD ["npm", "run", "dev"]